### ISSUE TITLE
Build issues on Windows

### ISSUE THREAD

**Issue by brechtsanders** [pgarner/libube#1]
I just tried to compile v1.0 on Windows with MinGW-w64 and encountered the following issues:

**1.**
Backtrace stuff was not available on my system so I disabled it in `lube/var.cpp` with the patch below. Maybe this should be made optional.
```
patch -ulbf lube/var.cpp << EOF
@@ -12,5 +12,7 @@
 #include <cstdarg>
 #include <stdexcept>
+#ifndef _WIN32
 #include <execinfo.h>
+#endif
 #include <cxxabi.h>

@@ -1537,4 +1539,5 @@
 void error::backTrace(std::ostream& iStream)
 {
+#ifndef _WIN32
     // Backtrace of more than a screenfull is probably not useful
     const int cBTSize = 64;
@@ -1591,4 +1594,5 @@
     free(buffer);
     free(symbol);
+#endif
 }

EOF
```

**2.**
On Windows `boost::filesystem::path` uses wide characters leading to errors like `error: invalid conversion from 'const value_type*' {aka 'const wchar_t*'} to 'int' [-fpermissive]` in `lube/path.cpp`.
This can be solved by using `.string().c_str()` instead of `.c_str()` on paths, as fixed with the patch below:
```
patch -ulbf lube/path.cpp << EOF
@@ -52,5 +52,5 @@
     var val;
-    val[2] = iPath.extension().c_str();
-    val[1] = iPath.stem().c_str();
-    val[0] = iPath.parent_path().c_str();
+    val[2] = iPath.extension().string().c_str();
+    val[1] = iPath.stem().string().c_str();
+    val[0] = iPath.parent_path().string().c_str();
     return val;
@@ -66,3 +66,3 @@
     for (fs::directory_iterator it(mPath); it != end; it++)
-        dir[it->path().c_str()] = iVal ? bits(it->path()) : nil;
+        dir[it->path().string().c_str()] = iVal ? bits(it->path()) : nil;
     return dir;
@@ -78,3 +78,3 @@
     {
-        dir[mPath.c_str()] = iVal ? bits(mPath) : nil;
+        dir[mPath.string().c_str()] = iVal ? bits(mPath) : nil;
         return dir;
@@ -84,3 +84,3 @@
     for (fs::recursive_directory_iterator it(mPath); it != end; it++)
-        dir[it->path().c_str()] = iVal ? bits(it->path()) : nil;
+        dir[it->path().string().c_str()] = iVal ? bits(it->path()) : nil;
     return dir;
@@ -102,5 +102,5 @@
         if (fs::is_directory(*it))
-            dir[it->path().filename().c_str()] = tree(*it);
+            dir[it->path().filename().string().c_str()] = tree(*it);
         else
-            dir[it->path().filename().c_str()] = nil;
+            dir[it->path().filename().string().c_str()] = nil;

EOF
```

**3.**
Various other warnings treated as errors, solved by removing `-Wall -Werror` in `CMakeLists.txt`.

**4.**
Not really an error, but I noticed `USE_STATIC` is checked as an environment variable. It would make more sense to allow passing this variable as a CMake variable using `-DUSE_STATIC:BOOL=ON`.

**Comment by pgarner** [comment]
Wow, thanks.  I had no idea anyone was interested in this.  So,
1. I put in a cmake check for the symbol rather than single out WIN32
2. The .c_str() is hacky (current feeling is lube should use std::string) so it's a hack on a hack, but patch applied verbatim.
3. I removed the compiler specific stuff that doesn't belong in CMakeLists.txt; it broke homebrew too.
4. Right.  I'm not even sure that USE_STATIC works, but problem for future me.
Version bumped to 1.0.1; maybe it works for you?

**Comment by brechtsanders** [comment]
Yes, 1.0.1 builds perfectly fine now on Windows without modifications. Thanks!
